POST https://api.openai.com/v1/images/generations
Authorization: Bearer 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
Content-Type: application/json

{
  "prompt": "Create an illustration that depicts a family of three generations (grandparents, parents, and children) discussing the different theories of attachment. In a style of a comics artwork",
  "n": 3,
  "size": "512x512",
  "user": "vladimir@kishlaly.com"
}