CREATE TABLE IF NOT EXISTS testings (
    id VARCHAR NOT NULL PRIMARY KEY,
    symbol VARCHAR(10),
    task_blocks TEXT,
    sl_strategy TEXT,
    tp_strategy TEXT,
    balance FLOAT8,
    successful_ratio FLOAT8,
    loss_ratio FLOAT8,
    all_positions_count FLOAT8,
    profitable_positions_count FLOAT8,
    loss_positions_count FLOAT8,
    min_position_duration_seconds FLOAT8,
    average_position_duration_seconds FLOAT8,
    max_position_duration_seconds FLOAT8,
    min_profit FLOAT8,
    avg_profit FLOAT8,
    max_profit FLOAT8,
    min_loss FLOAT8,
    avg_loss FLOAT8,
    max_loss FLOAT8,
    total_Loss FLOAT8,
    total_profit FLOAT8,
    average_roi FLOAT8,
    signal_stats TEXT
);